2020-05-11 15:03:28.705 [error] <0.275.0> gen_server <0.275.0> terminated with reason: {socket_error,timeout}
2020-05-11 15:03:28.705 [error] <0.269.0> gen_server <0.269.0> terminated with reason: {socket_error,timeout}
2020-05-11 15:03:28.729 [error] <0.269.0> CRASH REPORT Process <0.269.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-05-11 15:03:28.730 [error] <0.267.0> Supervisor {<0.267.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.268.0>, {amqp_params_network,<<"guest">>,<<"UsgidtrmxtnW3BQaNv/c2IB2nIpSKBlj2oCT8AZc4R/BKyawHlh5pnIyADECIo...">>,...}) at <0.269.0> exit with reason {socket_error,timeout} in context child_terminated
2020-05-11 15:03:28.731 [error] <0.267.0> Supervisor {<0.267.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.268.0>, {amqp_params_network,<<"guest">>,<<"UsgidtrmxtnW3BQaNv/c2IB2nIpSKBlj2oCT8AZc4R/BKyawHlh5pnIyADECIo...">>,...}) at <0.269.0> exit with reason reached_max_restart_intensity in context shutdown
